
# https://github.com/rmarting/strimzi-demo/blob/master/strimzi-cr/kafka-cluster.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster-one
  annotations:
    strimzi.io/node-pools: disabled
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
      num.partitions: 1
      auto.create.topics.enable: false
      log.retention.hours: 24
      log.cleanup.policy: delete
      log.cleaner.enable: true
      log.cleaner.delete.retention.ms: 86400000
      log.message.format.version: "2.7"
    jvmOptions:
      "-Xms": "2g"
      "-Xmx": "2g"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

