
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: minikube-crossplane-provider-aws-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: my-aws-secret

